# Reference: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/expenses_tracker
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    username: macy
    password: macy

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
# App Properties
example:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000