server:
  port: 8040
  servlet:
    context-path: /users
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  application:
    name: ExpenseTracker
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    change-log: classpath:/db/main_changelog.xml